server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: HospitalMedicalRecords
  groovy:
    template:
      check-template-location: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        id:
          new_generator_mappings: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    database: mysql

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmr
    username: sa
    password: password

  liquibase:
    contexts: dev, faker
    change-log: db/changelog/db-changelog.xml
    default-schema: hmr
  sql:
    init:
      continue-on-error: false
      mode: always

rsa:
  key:
    privateKeyFile: 'src/main/resources/private_key.key'
    publicKeyFile: 'src/main/resources/public_key.pub'

token:
  header: 'Authorization'
  expiration: 3600
  refreshExpiration: 10000000