server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: HospitalMedicalRecords
  groovy:
    template:
      check-template-location: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: false
        id:
          new_generator_mappings: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    database: mysql

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmr
    username: sa
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  liquibase:
    contexts: dev, faker
    change-log: db/changelog/db-changelog.xml
    default-schema: hmr
  sql:
    init:
      continue-on-error: false
      mode: always

token:
  header: 'Authorization'
  expiration: 86400000
  refreshExpiration: 10000000
  secret: OWNlOTkwNzA0NWZkNmYzMjdmZGZmNjc1ZjgzZGVjNjE1MDU4OGI2NjUzOTJiMTIzOTA1ODlmZjEzMjNlMDBjMzFkMDExOGVmZTU1MTQ2OGE3NDFmMzk3YzQ1ZWRjYWNiMWU5ZTc5YzdiNTQxOWJlZjk0MzdmYTYzZjk1MWJlNWU=