server:
  port: 8082
  servlet:
    context-path: /api


spring:
  application:
    name: HospitalMedicalRecords
  groovy:
    template:
      check-template-location: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        id:
          new_generator_mappings: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:../hmr
    username: sa
    password:
    driverClassName: org.h2.Driver
  liquibase:
    contexts: dev, faker
    change-log: db/changelog/db-changelog.xml
