server:
  port: 8082
spring:
  application:
    name: HospitalMedicalRecords
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:../hms
    username: sa
    password:
    driverClassName: org.h2.Driver
  liquibase:
    contexts: dev, faker


